language: node_js
node_js:
    - "0.11"
    - "0.10"
# before_script:
#    - npm install -g gulp
#script: gulp
before_script:
  - npm install -g react-tools
script: ./travis-test.sh

notifications:
    slack:
      rooms:
        - buildo:iVeL8b7n4t8Mkif5nJmHmsix#frontends
